### ISSUE TITLE
Errors with SingleDatePicker & DayPicker

### ISSUE THREAD

**Issue by IgnusG** [kurdin/inferno-dates#2]
I'm getting these 2 errors when I click on the input:
```
SingleDatePicker.js:443 
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at SingleDatePicker.responsivizePickerPosition
```
and
```
DayPicker.js:642
Uncaught (in promise) TypeError: Cannot read property 'querySelectorAll' of undefined
    at DayPicker.adjustDayPickerHeight
````

This is the way I'm using it now:
```jsx
import 'inferno-dates/css/styles.scss';
import { SingleDatePicker } from 'inferno-dates';

class DateTime extends Component {
  constructor(props) {
    super(props);

    this.state = {
      focused: false
    };
  }

  render() {
    return (
        <SingleDatePicker
          date={moment(this.props.value).unix()}
          displayFormat='L'
          onDateChange={this.props.onChange}
          focused={this.state.focused}
          onFocusChange={({ focused }) => this.setState({ focused })}
        />
    );
  }
}

```

**Comment by kurdin** [comment]
I will take a look. Right now I use only `DateRangePicker` component and it works well.

**Comment by kurdin** [comment]
@IgnusG try to wrap SingleDatePicker same way they did it on examples/SingleDatePickerWrapper.jsx I use DateRangePickerWrapper.jsx as well for my needs.

Copy code from source of `node_modules/inferno-dates/examples/SingleDatePickerWrapper.jsx`  and replace `../src/`  with `inferno-dates/lib/` then use exported `SingleDatePickerWrapper` component instead of `SingleDatePicker`
